spring:
  ai:
    gigachat:
      scope: GIGACHAT_API_PERS
      client-id: ${SPRING_AI_GIGACHAT_CLIENT_ID}
      client-secret: ${SPRING_AI_GIGACHAT_CLIENT_SECRET}
      unsafe-ssl: true
      chat:
        options:
          model: GigaChat-2-Max
