spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:gigachat-openrouter}

management:
  tracing:
    sampling:
      probability: 1
  otlp:
    tracing:
      export:
        enabled: ${MANAGEMENT_OTLP_TRACING_EXPORT_ENABLED:false}
      transport: ${MANAGEMENT_OTLP_TRACING_TRANSPORT:http}
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:localhost:8080}
  endpoint:
    health:
      probes:
        enabled: true
  observations:
    annotations:
      enabled: true

spring.ai.gigachat:
  scope: ${SPRING_AI_GIGACHAT_SCOPE:GIGACHAT_API_CORP}
  client-id: ${SPRING_AI_GIGACHAT_CLIENT_ID}
  client-secret: ${SPRING_AI_GIGACHAT_CLIENT_SECRET}
  unsafe-ssl: ${SPRING_AI_GIGACHAT_UNSAFE_SSL:true}
  chat:
    options:
      model: ${SPRING_AI_GIGACHAT_MODEL:GigaChat-2-Max}
      temperature: ${SPRING_AI_GIGACHAT_TEMPERATURE:0.95}
      top-p: ${SPRING_AI_GIGACHAT_TOP_P:0.95}
      max-tokens: ${SPRING_AI_GIGACHAT_MAX_TOKENS:1500}

spring.ai.openai:
  base-url: ${OPENROUTER_BASE_URL:https://openrouter.ai/api}
  api-key: ${OPENROUTER_API_KEY}
  chat:
    options:
      model: ${OPENROUTER_MODEL:deepseek/deepseek-r1}
      temperature: ${OPENROUTER_TEMPERATURE:0.5}
      max-tokens: ${OPENROUTER_MAX_TOKENS:1000}

ai:
  model-routing:
    nodes:
      ReasonAndRouteNode: ${AI_ROUTE_REASON_MODEL:deepseek/deepseek-r1}
      ValidateJsonSchemaNode: ${AI_ROUTE_VALIDATE_SCHEMA_MODEL:deepseek/deepseek-r1}
      VerifyJsonByJsonSchemaNode: ${AI_ROUTE_VALIDATE_JSON_MODEL:deepseek/deepseek-r1}
      ThinkHowToGenerateTool: ${AI_ROUTE_THINK_GEN_MODEL:deepseek/deepseek-r1}
      ThinkHowToFixJsonTool: ${AI_ROUTE_THINK_FIX_MODEL:deepseek/deepseek-r1}
      GenerateJsonBySchemaTool: ${AI_ROUTE_GENERATE_MODEL:GigaChat-2-Max}
      FixValidationErrorsInJsonTool: ${AI_ROUTE_FIX_MODEL:GigaChat-2-Max}